export const CONFIG = {
	GAMEPLAY: {
		START_SPEED: 10,
	},
	RENDER: {
		PASS: {
			THRESHOLD: 0,
			STRENGTH: 0.5,
			RADIUS: 0,
			EXPOSURE: 1,
		},
	},
	PLAYER: {
		// SPEED: 10,
	},
	CONTROLS: {
		ROTATION_SPEED: 1,
		MAX_ROTATION: Math.PI / 4,
		ROTATION_RETURN_SPEED: 0.01,
	},
	BACKGROUND: {
		ROTATION_SPEED: 0.03,
	},
	OBSTACLES: {
		MAX_Z_ROTATION: 0.01,
		COLORS: [0xff0000, 0x00ff00, 0x0000ff],
	},
	CAMERA: {
		LERP_SPEED: 0.1,
	},
	SERVER_RECON: {
		HEARTBEAT_MS: 200,
		POSITION_LERP_FACTOR: 0.3,
	},
};
