export const CONFIG = {
	GAMEPLAY: {},
	RENDER: {
		PASS: {
			THRESHOLD: 0,
			STRENGTH: 1,
			RADIUS: 0,
			EXPOSURE: 1,
		},
	},
	CONTROLS: {
		ROTATION_SPEED: 0.01,
		MAX_ROTATION: Math.PI / 4,
		ROTATION_RETURN_SPEED: 0.01,
	},
	BACKGROUND: {
		MOVEMENT_SPEED: 1,
	},
	OBSTACLES: {
		MAX_Z_ROTATION: 0.01,
		COLORS: [0xff0000, 0x00ff00, 0x0000ff],
	},
	CAMERA: {
		LERP_SPEED: 0.03,
	},
};
